### ISSUE TITLE
[Todo list] Turn off the Global Sprint data script 

### ISSUE THREAD

**Issue by patjouk** [mozilla/network-pulse-api#363]
Ref: #361 
When it's safe to turn it off (@acabunoc can you remind me when we can do it?), we need to:

- [x] Stop the scheduled task on staging and prod
- [x] Remove the alerts on logentries
- [x] Remove code
- [x] Clean the env var for staging
- [x] Clean the env var for prod

CC @cadecairos

**Comment by acabunoc** [comment]
End of June, thanks!

**Comment by patjouk** [comment]
Done. The spreadsheet is still available on S3 but everything else was removed.
